export enum XeroClientExceptionCode {
  CONNECTION_NOT_FOUND = 'XERO_CONNECTION_NOT_FOUND',
  TOKEN_EXPIRED = 'XERO_TOKEN_EXPIRED',
  INVALID_CREDENTIALS = 'XERO_INVALID_CREDENTIALS',
  API_ERROR = 'XERO_API_ERROR',
  RATE_LIMIT_EXCEEDED = 'XERO_RATE_LIMIT_EXCEEDED',
  NETWORK_ERROR = 'XERO_NETWORK_ERROR',
  INVALID_RESPONSE = 'XERO_INVALID_RESPONSE',
}
