import type { Property } from '../types/property-map.types';

export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    addressDisplay: '123 Main St, Sydney NSW 2000',
    addressStreet: '123 Main St',
    addressSuburb: 'Sydney',
    addressState: 'NSW',
    addressPostcode: '2000',
    addressCountry: 'Australia',
    latitude: -33.8688,
    longitude: 151.2093,
    listingStatus: 'on_market',
    askingPrice: 1200000,
    soldPrice: null,
    landSize: 450,
    floorArea: 180,
    photos: ['https://example.com/property1.jpg'],
    description: 'Beautiful family home',
    attributes: {
      bedrooms: 3,
      bathrooms: 2,
      carSpaces: 2,
      propertyType: 'house',
      features: ['pool', 'garden'],
    },
    sourceUrl: 'https://example.com/prop1',
    sourceId: 'ext-1',
    listedDate: '2024-01-15',
    soldDate: null,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'prop-2',
    addressDisplay: '456 George St, Sydney NSW 2000',
    addressStreet: '456 George St',
    addressSuburb: 'Sydney',
    addressState: 'NSW',
    addressPostcode: '2000',
    addressCountry: 'Australia',
    latitude: -33.8670,
    longitude: 151.2070,
    listingStatus: 'on_market',
    askingPrice: 850000,
    soldPrice: null,
    landSize: null,
    floorArea: 95,
    photos: ['https://example.com/property2.jpg'],
    description: 'Modern apartment in CBD',
    attributes: {
      bedrooms: 2,
      bathrooms: 1,
      carSpaces: 1,
      propertyType: 'apartment',
      features: ['balcony', 'gym'],
    },
    sourceUrl: 'https://example.com/prop2',
    sourceId: 'ext-2',
    listedDate: '2024-01-20',
    soldDate: null,
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-01-20T00:00:00Z',
  },
  {
    id: 'prop-3',
    addressDisplay: '789 Pitt St, Sydney NSW 2000',
    addressStreet: '789 Pitt St',
    addressSuburb: 'Sydney',
    addressState: 'NSW',
    addressPostcode: '2000',
    addressCountry: 'Australia',
    latitude: -33.8710,
    longitude: 151.2110,
    listingStatus: 'on_market',
    askingPrice: 2500000,
    soldPrice: null,
    landSize: 650,
    floorArea: 250,
    photos: ['https://example.com/property3.jpg'],
    description: 'Luxury family estate',
    attributes: {
      bedrooms: 4,
      bathrooms: 3,
      carSpaces: 3,
      propertyType: 'house',
      features: ['pool', 'tennis court', 'wine cellar'],
    },
    sourceUrl: 'https://example.com/prop3',
    sourceId: 'ext-3',
    listedDate: '2024-01-10',
    soldDate: null,
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'prop-4',
    addressDisplay: '321 Kent St, Sydney NSW 2000',
    addressStreet: '321 Kent St',
    addressSuburb: 'Sydney',
    addressState: 'NSW',
    addressPostcode: '2000',
    addressCountry: 'Australia',
    latitude: -33.8650,
    longitude: 151.2050,
    listingStatus: 'on_market',
    askingPrice: 950000,
    soldPrice: null,
    landSize: null,
    floorArea: 110,
    photos: ['https://example.com/property4.jpg'],
    description: 'Spacious apartment with views',
    attributes: {
      bedrooms: 2,
      bathrooms: 2,
      carSpaces: 1,
      propertyType: 'apartment',
      features: ['harbour view', 'concierge'],
    },
    sourceUrl: 'https://example.com/prop4',
    sourceId: 'ext-4',
    listedDate: '2024-01-18',
    soldDate: null,
    createdAt: '2024-01-18T00:00:00Z',
    updatedAt: '2024-01-18T00:00:00Z',
  },
  {
    id: 'prop-5',
    addressDisplay: '555 Liverpool St, Sydney NSW 2000',
    addressStreet: '555 Liverpool St',
    addressSuburb: 'Sydney',
    addressState: 'NSW',
    addressPostcode: '2000',
    addressCountry: 'Australia',
    latitude: -33.8695,
    longitude: 151.2080,
    listingStatus: 'on_market',
    askingPrice: 1500000,
    soldPrice: null,
    landSize: 520,
    floorArea: 200,
    photos: ['https://example.com/property5.jpg'],
    description: 'Contemporary townhouse',
    attributes: {
      bedrooms: 3,
      bathrooms: 2,
      carSpaces: 2,
      propertyType: 'townhouse',
      features: ['courtyard', 'rooftop terrace'],
    },
    sourceUrl: 'https://example.com/prop5',
    sourceId: 'ext-5',
    listedDate: '2024-01-12',
    soldDate: null,
    createdAt: '2024-01-12T00:00:00Z',
    updatedAt: '2024-01-12T00:00:00Z',
  },
];

export const mockPropertyResponse = {
  data: {
    properties: {
      edges: mockProperties.map((property) => ({
        node: property,
      })),
      pageInfo: {
        hasNextPage: false,
        hasPreviousPage: false,
        startCursor: 'cursor-start',
        endCursor: 'cursor-end',
      },
      totalCount: mockProperties.length,
    },
  },
};

export const createMockProperty = (overrides?: Partial<Property>): Property => ({
  id: 'mock-prop-id',
  addressDisplay: '123 Test St, Sydney NSW 2000',
  addressStreet: '123 Test St',
  addressSuburb: 'Sydney',
  addressState: 'NSW',
  addressPostcode: '2000',
  addressCountry: 'Australia',
  latitude: -33.8688,
  longitude: 151.2093,
  listingStatus: 'on_market',
  askingPrice: 1000000,
  soldPrice: null,
  landSize: 400,
  floorArea: 150,
  photos: ['https://example.com/test.jpg'],
  description: 'Test property',
  attributes: {
    bedrooms: 3,
    bathrooms: 2,
    carSpaces: 2,
    propertyType: 'house',
    features: [],
  },
  sourceUrl: 'https://example.com/test',
  sourceId: 'test-1',
  listedDate: '2024-01-01',
  soldDate: null,
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
  ...overrides,
});
