export {
  PROPERTY_MAP_FRAGMENT,
  PROPERTIES_IN_BOUNDING_BOX,
  PROPERTIES_WITHIN_RADIUS,
  PROPERTIES_IN_POLYGON,
  GET_PROPERTY,
  FIND_PROPERTIES_IN_BOUNDS,
  GET_PROPERTY_DETAILS,
} from './property-map.queries';
